version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: nestjs_prod_app
    ports:
      - "${APP_PORT}:3000"
    environment:
      - NODE_ENV=production
    volumes:
      - .:/usr/src/app
      - ./uploads:/usr/src/app/uploads
